export const RULES = {
  artistReleaseRoles: {
    // Roles that should not be considered
    reject: ["TrackAppearance", "UnofficialRelease"],
  },
  genres: {
    // Genres that must not be included
    reject: ["Non-Music"],
  },
  formats: {
    // Main formats. Since a release can have multiple of this formats
    // (eg. Compilation + Album), the first found in this list will be considered
    // the main format.
    // Album is last because if it's anything else (eg. Compilation + Album),
    // then it's not a "core" album.
    mainSortedByConsiderationOrder: [
      "Single",
      "Maxi-Single",
      "EP",
      "Compilation",
      "Unknown",
      "Album",
    ],
    // One of these has to appear for a format to be considered valid
    accept: ["CD", "Vinyl"],
    // None of these must appear for a format to be considered valid
    reject: [
      "4-Track Cartridge",
      "8-Track Cartridge",
      "Acetate",
      "Beta ED",
      "Betacam SP",
      "Betacam",
      "Betamax",
      "Blu-ray-R",
      "Blu-ray",
      "Box Set",
      "Cartrivision",
      "Cassette",
      "CD-ROM",
      "CDr",
      "CDV",
      "Cylinder",
      "DAT",
      "DC-International",
      "DCC",
      "DVD-Video",
      "DVD",
      "DVDr",
      "Edison Disc",
      "Elcaset",
      "File",
      "Film Reel",
      "Flexi-disc",
      "Floppy Disk",
      "HD DVD-R",
      "HD DVD",
      "HitClips",
      "Laserdisc",
      "Lathe Cut",
      "Memory Stick",
      "Microcassette",
      "Mighty Tiny",
      "Minidisc",
      "MiniDV",
      "MVD",
      "NT Cassette",
      "Pathé Disc",
      "PlayTape",
      "Pocket Rocker",
      "Promo",
      "RCA Tape Cartridge",
      "Reel-To-Reel",
      "Revere Magnetic Stereo Tape Ca",
      "Sabamobil",
      "SACD",
      "SelectaVision",
      "Shellac",
      "Sopic",
      "Super Beta",
      "Super VHS",
      "TeD",
      "Tefifon",
      "Test Pressing",
      "U-matic",
      "Ultra HD Blu-ray",
      "UMD",
      "VHD",
      "VHS",
      "Video 2000",
      "Video8",
      "Wire Recording",
      "Zip Disk",
    ],
    // None of this formats must appear in the whole format list of the release
    eliminatory: [
      "Club Edition",
      "Enhanced",
      "Transcription",
      "Limited Edition",
      "Mispress",
      "Promo",
      "Record Store Day",
      "Reissue",
      "Remixed",
      "Repress",
      "Test Pressing",
      "Tour Recording",
      "Unofficial Release",
    ],
  },
  // Title endings that will invalidate the track in the tracklist
  ignoreTracksEndingWith: [
    "Bonus Video",
    "Documentary",
    "Edit",
    "Ending",
    "Medley",
    "Mix",
    "Solo",
    "Version",
    "Untitled",
  ],
};
